config/routes.rb
Rails.application.routes.draw do

resources :departamentos
root to: "produtos#index"

resources :produtos, only: [:new,:create,:destroy,:edit,:update]

get "produtos/busca", to: "produtos#busca", as: :busca_produto

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord

  belongs_to :departamento, optional: true

  validates :preco, presence: true
  validates :nome, length: {minimum: 4}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @produtos_por_departamento = Produto.where("departamento_id = ?", params[:id])
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  before_action :set_produto, only:[:edit,:update,:destroy]



  def index
    @produtos = Produto.order(nome: :asc)
    @produto_com_desconto = Produto.order(preco: :asc).limit 1
  end

  def new
    @produto = Produto.new
    @departamento = Departamento.all
  end

  def create
    @produto = Produto.new produto_params
    if @produto.save
      flash[:notice] = "Produto cadastrado com sucesso!"
      redirect_to root_path
    else
      renderiza :new
    end
  end

  def destroy
    @produto.destroy
    flash[:notice] = "Produto removido com sucesso!"
    redirect_to root_path
  end

  def busca
    @nome = params[:nome]
    @produtos = Produto.where "nome like ?", "%#{@nome}%"
  end


  def edit
    renderiza :edit
  end

  def update
    if @produto.update produto_params
      flash[:notice] = "Produto atualizado com sucesso!"
      redirect_to root_path
    else
      renderiza :edit
    end
  end

private

def produto_params
  params.require(:produto).permit(:nome,:descricao,:preco,:quantidade,:departamento_id)
end

def set_produto
  @produto = Produto.find(params[:id])
end

def renderiza(view)
  @departamento = Departamento.all
  render view
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento, local: true) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :departamento_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Mostrar Produtos', departamento, class:"btn btn-default" %></td>
        <td><%= link_to 'Editar', edit_departamento_path(departamento),class:"btn btn-default" %></td>
        <td><%= link_to 'Remover', departamento, method: :delete,class:"btn btn-default", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Departamento', new_departamento_path, class:"btn btn-default" %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-hover">
  <h2>Produtos</h2>
  <thead>
    <tr>
      <td>Nome</td>
      <td>Descrição</td>
      <td>Departamento</td>
      <td>Preço</td>
      <td>Quantidade</td>
      <td colspan="2"></td>
    </tr>
  </thead>
  <tbody>
    <%= render @produtos_por_departamento %>
  </tbody>
</table>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mercantil</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>


      <%= nav_bar brand: "Inicio", brand_link: root_path do %>
          <%= menu_group do %>
              <%= menu_item "Novo Produto", new_produto_path %>
              <%= menu_item "Departamentos", departamentos_path %>
          <% end %>

          <%= form_tag busca_produto_path, method: :get, class:"navbar-form navbar-right" do %>
              <div class="form-group">
                <%= text_field_tag :nome, @nome, class:"form-control"%>
                <%= button_to "Buscar", nil, class:"btn btn-default" %>
              </div>
          <% end %>




      <% end %>
      <div class="container">


    <%= yield %>

    </div>
  </body>
</html>

app/views/produtos/_form.html.erb
<% @produto.errors.full_messages.each do |msg| %>
<div class="alert alert-danger">
  <%= msg %>
</div>
<% end %>


<%= form_for @produto do |form|%>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :nome %>
        <%= form.text_field :nome, class:"form-control"%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :descricao %>
        <%= form.text_area :descricao, class:"form-control", rows:4%>
      </div>
    </div>
  </div>


<div class="row">
  <div class="col-sm-2">
    <div class="form-group">
      <%= form.label :departamento %>
      <%= form.collection_select :departamento_id, @departamento,:id,:nome,{}, class:"form-control"  %>
    </div>
  </div>
</div>


  <div class="row">
    <div class="col-sm-3">
      <div class="form-group">
        <%= form.label :preco %>
        <%= form.number_field :preco, class:"form-control", step:0.01%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3">
      <div class="form-group">
        <%= form.label :quantidade %>
        <%= form.number_field :quantidade, class:"form-control"%>
      </div>
    </div>
  </div>

  <%= form.submit texto_da_acao, class:"btn btn-primary"%>

<% end %>

app/views/produtos/_produto.html.erb
<tr>
  <td><%= produto.nome %></td>
  <td><%= produto.descricao %></td>
  <td><%= produto.departamento.nome %></td>
  <td><%= produto.preco %></td>
  <td><%= produto.quantidade %></td>
    <td><%= link_to "Alterar", edit_produto_path(produto), class:"btn btn-default" %></td>
    <td><%= button_to "Remover", produto, method: :delete, class:"btn btn-danger",
      data: {confirm: "Você tem certeza que deseja remover o produto #{produto.nome}?"}%></td>
</tr>

app/views/produtos/busca.html.erb
<table class="table table-bordered table-hover">
  <h2>Produtos</h2>
  <thead>
    <tr>
      <td>Nome</td>
      <td>Descrição</td>
      <td>Departamento</td>
      <td>Preço</td>
      <td>Quantidade</td>
      <td colspan="2"></td>
    </tr>
  </thead>
  <tbody>
    <%= render @produtos %>
  </tbody>
</table>

app/views/produtos/edit.html.erb
<%= render partial: "form", locals: {texto_da_acao: "Atualizar"}%>

app/views/produtos/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
      <%= flash[:notice] %>
  </div>
<% end %>


<table class="table table-bordered table-hover">
  <h2>Produtos</h2>
  <thead>
    <tr>
      <td>Nome</td>
      <td>Descrição</td>
      <td>Departamento</td>
      <td>Preço</td>
      <td>Quantidade</td>
      <td colspan="2"></td>
    </tr>
  </thead>
  <tbody>
    <%= render @produtos %>
  </tbody>
</table>

<table class="table table-bordered table-hover">
  <div class="alert alert-success">
        <h2 class="alert-heading">Produtos com desconto</h2>
  </div>

  <thead>
    <tr>
      <td>Nome</td>
      <td>Descrição</td>
      <td>Departamento</td>
      <td>Preço</td>
      <td>Quantidade</td>
      <td colspan="2"></td>
    </tr>
  </thead>
  <tbody>
      <%= render @produto_com_desconto%>
  </tbody>
</table>

app/views/produtos/new.html.erb
<%= render partial: "form", locals: {texto_da_acao: "Criar"}%>